// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetAdminGitfilesData, GetAdminGitfilesResponse, PostAdminGitfilesManualData, PostAdminGitfilesManualResponse, PostAdminGitfilesManualError, PostAdminGitfilesStartData, PostAdminGitfilesStartResponse, PostAdminGitfilesStartError, GetAdminGitfilesStatusData, GetAdminGitfilesStatusResponse, GetAdminGitfilesStatusError, PostAdminGitfilesStopData, PostAdminGitfilesStopResponse, PostAdminGitfilesStopError, GetHistoriesData, GetHistoriesResponse, GetRankingsData, GetRankingsResponse, GetResultsData, GetResultsResponse, GetResultsByScoreidData, GetResultsByScoreidResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
};

/**
 * Get Git File List
 */
export const getAdminGitfiles = <ThrowOnError extends boolean = false>(options?: Options<GetAdminGitfilesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAdminGitfilesResponse, unknown, ThrowOnError>({
        url: '/admin/gitfiles',
        ...options
    });
};

/**
 * Append to collector manual list
 */
export const postAdminGitfilesManual = <ThrowOnError extends boolean = false>(options: Options<PostAdminGitfilesManualData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostAdminGitfilesManualResponse, PostAdminGitfilesManualError, ThrowOnError>({
        url: '/admin/gitfiles/manual',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Start Git File Collector
 * Starts the Git File collection process
 */
export const postAdminGitfilesStart = <ThrowOnError extends boolean = false>(options?: Options<PostAdminGitfilesStartData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostAdminGitfilesStartResponse, PostAdminGitfilesStartError, ThrowOnError>({
        url: '/admin/gitfiles/start',
        ...options
    });
};

/**
 * Get git files statistics and collector status
 */
export const getAdminGitfilesStatus = <ThrowOnError extends boolean = false>(options?: Options<GetAdminGitfilesStatusData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAdminGitfilesStatusResponse, GetAdminGitfilesStatusError, ThrowOnError>({
        url: '/admin/gitfiles/status',
        ...options
    });
};

/**
 * Stop Git File Collector
 * Stops the Git File collection process
 */
export const postAdminGitfilesStop = <ThrowOnError extends boolean = false>(options?: Options<PostAdminGitfilesStopData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostAdminGitfilesStopResponse, PostAdminGitfilesStopError, ThrowOnError>({
        url: '/admin/gitfiles/stop',
        ...options
    });
};

/**
 * Get score histories
 * Get score histories by git link
 */
export const getHistories = <ThrowOnError extends boolean = false>(options: Options<GetHistoriesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetHistoriesResponse, unknown, ThrowOnError>({
        url: '/histories',
        ...options
    });
};

/**
 * Get ranking results
 * Get ranking results, optionally including all details
 */
export const getRankings = <ThrowOnError extends boolean = false>(options?: Options<GetRankingsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetRankingsResponse, unknown, ThrowOnError>({
        url: '/rankings',
        ...options
    });
};

/**
 * Search score results by git link
 * Search score results by git link
 * NOTE: All details are ignored, should use /results/:scoreid to get details
 * NOTE: Maxium take count is 1000
 */
export const getResults = <ThrowOnError extends boolean = false>(options: Options<GetResultsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetResultsResponse, unknown, ThrowOnError>({
        url: '/results',
        ...options
    });
};

/**
 * Get score results
 * Get score results, including all details by scoreid
 */
export const getResultsByScoreid = <ThrowOnError extends boolean = false>(options: Options<GetResultsByScoreidData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetResultsByScoreidResponse, unknown, ThrowOnError>({
        url: '/results/{scoreid}',
        ...options
    });
};