ALTER TABLE debian_packages 
ADD COLUMN dl_3m_vol BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE arch_packages 
ADD COLUMN dl_3m_vol BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE homebrew_packages 
ADD COLUMN dl_3m_vol BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE gentoo_packages 
ADD COLUMN dl_3m_vol BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE alpine_packages 
ADD COLUMN dl_3m_vol BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE nix_packages 
ADD COLUMN dl_3m_vol BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE ubuntu_packages 
ADD COLUMN dl_3m_vol BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE fedora_packages 
ADD COLUMN dl_3m_vol BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE deepin_packages 
ADD COLUMN dl_3m_vol BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE centos_packages 
ADD COLUMN dl_3m_vol BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE aur_packages 
ADD COLUMN dl_3m_vol BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE openeuler_packages 
ADD COLUMN dl_3m_vol BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE openkylin_packages 
ADD COLUMN dl_3m_vol BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE openanolis_packages 
ADD COLUMN dl_3m_vol BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE opencloudos_packages 
ADD COLUMN dl_3m_vol BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE openharmony_packages 
ADD COLUMN dl_3m_vol BIGINT DEFAULT 0 NOT NULL;
